# -*- coding: utf-8 -*-
"""AYGAZ_PROJE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-9p88KAntMeUyRFr0vIYd099MLjitgR
"""

from IPython import get_ipython
from IPython.display import display

import numpy as np # type: ignore
import os
import random
from tensorflow.keras.preprocessing.image import ImageDataGenerator # type: ignore
import tensorflow as tf # type: ignore
from tensorflow.keras import layers, models # type: ignore
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, MaxPool2D # type: ignore
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint # type: ignore
from tensorflow.keras.optimizers import Adam # type: ignore
import matplotlib.pyplot as plt # type: ignore
import cv2 # type: ignore

"""Dosya Gamze Cbs Yz içinde"""

from google.colab import files
files.upload()  # kaggle.json dosyasını yükle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d yessicatuteja/skycity-the-city-landscape-dataset

!unzip skycity-the-city-landscape-dataset.zip -d skycity_dataset

def data_load(data_directory):
    """
    Load class names and create a dictionary mapping class names to labels.

    Args:
    data_directory (str): Path to the dataset directory.

    Returns:
    tuple: A tuple containing a list of class names and a dictionary mapping class names to labels.
    """
    classes = os.listdir(data_directory)
    label_classes = {cls: idx for idx, cls in enumerate(classes)}
    return classes, label_classes

def data_prep(data_directory, classes, target_size=(128, 128), batch_size=32, validation_split=0.2):
    """
    Prepare the data generators for training and validation.

    Args:
    data_directory (str): Path to the dataset directory.
    classes (list): List of class labels (folder names) in dataset.
    target_size (tuple): Desired image size.
    batch_size (int): Number of samples per batch.
    validation_split (float): Fraction of data to use for validation.

    Returns:
    tuple: Training and validation data generators.
    """
    image_dt_gen = ImageDataGenerator(rescale=1.0/255.0, validation_split=validation_split)


    train_generator = image_dt_gen.flow_from_directory(
        data_directory,
        target_size=target_size,
        batch_size=batch_size,
        class_mode='categorical',
        subset='training'
    )

    validation_generator = image_dt_gen.flow_from_directory(
        data_directory,
        target_size=target_size,
        batch_size=batch_size,
        class_mode='categorical',
        subset='validation'
    )

    num_classes = len(classes)
    class_labels = list(train_generator.class_indices.keys())

    print("Number of classes:", num_classes)
    print("Class labels:", class_labels)


    return train_generator, validation_generator

def split_data(generator):
    """
    Split data into features (X) and labels (y).

    Args:
    generator (ImageDataGenerator): Data generator.

    Returns:
    tuple: Features and labels as numpy arrays.
    """
    X, y = [], []

    for i in range(len(generator)):
        batch_images, batch_labels = generator[i]
        X.extend(batch_images)
        y.extend(batch_labels)

    X = np.array(X)
    y = np.array(y)
    y = np.argmax(y, axis=1)

    print(f'İmage shape: {X.shape}')

    return X, y

def visualize_images_with_labels(directory, num_images=20, font_size=15):
    """
    Visualize a random selection of images with their corresponding labels.

    Args:
    directory (str): Path to the dataset directory.
    num_images (int): Number of images to visualize.
    font_size (int): Font size for labels.
    """
    datagen = ImageDataGenerator(rescale=1/255)
    data_generator = datagen.flow_from_directory(
        directory,
        target_size=(256, 256),
        batch_size=1,
        class_mode='categorical',
        shuffle=True
    )
    class_indices = {v: k for k, v in data_generator.class_indices.items()}
    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for i in range(num_images):
        image, label = next(data_generator)
        axes[i].imshow(image[0])
        label = int(np.argmax(label[0]))
        axes[i].set_title(class_indices[label], fontsize=font_size)
        axes[i].axis('off')

    plt.tight_layout()
    plt.show()

def build_model(input_shape=(128, 128, 3), num_classes=10):
    """
    Build a convolutional neural network model.

    Args:
    input_shape (tuple): Shape of the input images.
    num_classes (int): Number of output classes.

    Returns:
    Sequential: The model berfore it is compiled.
    """
    model = Sequential([
        Conv2D(32, (3, 3), padding="Same", activation="relu", input_shape=input_shape),
        MaxPool2D(pool_size=(2, 2)),
        Dropout(0.2),

        Conv2D(64, (3, 3), padding="Same", activation="relu"),
        MaxPool2D(pool_size=(2, 2)),
        Dropout(0.3),

        Conv2D(128, (3, 3), padding="Same", activation="relu"),
        MaxPool2D(pool_size=(2, 2), strides=(2, 2)),
        Dropout(0.4),

        Conv2D(256, (3, 3), padding="Same", activation="relu"),
        MaxPool2D(pool_size=(2, 2), strides=(2, 2)),
        Dropout(0.5),

        Flatten(),
        Dense(512, activation="relu"),
        Dropout(0.5),
        Dense(num_classes, activation="softmax")
    ])
    return model

def train_model_with_best_accuracy(model, X_train, y_train, X_val, y_val, epochs=50, checkpoint_path='best_model.keras'):
    """
    Train the model with early stopping and save the best model based on validation accuracy.

    Args:
    model (Sequential): The compiled model.
    X_train (ndarray): Training data.
    y_train (ndarray): Training labels.
    X_val (ndarray): Validation data.
    y_val (ndarray): Validation labels.
    epochs (int): Number of training epochs.
    checkpoint_path (str): Path to save the best model.

    Returns:
    tuple: Trained model and training history.
    """
    num_classes = np.max(y_train) + 1
    y_train_onehot = tf.keras.utils.to_categorical(y_train, num_classes=num_classes)
    y_val_onehot = tf.keras.utils.to_categorical(y_val, num_classes=num_classes)

    early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    model_checkpoint = ModelCheckpoint(filepath=checkpoint_path, monitor='val_accuracy', save_best_only=True, mode='max')

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    history = model.fit(X_train, y_train_onehot, epochs=epochs, validation_data=(X_val, y_val_onehot), callbacks=[early_stopping, model_checkpoint])

    return model, history

def plot_accuracy(history):
    """
    Plot training and validation accuracy over epochs.

    Args:
    history (History): Training history.
    """
    plt.figure()
    plt.plot(history.history["accuracy"], label="Train Accuracy")
    if 'val_accuracy' in history.history:
        plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.title("Model Accuracy")
    plt.show()

def plot_loss(history):
    """
    Plot training and validation loss over epochs.

    Args:
    history (History): Training history.
    """
    plt.figure()
    plt.plot(history.history["loss"], label="Train Loss")
    if 'val_loss' in history.history:
        plt.plot(history.history["val_loss"], label="Validation Loss")
    plt.xlabel("Epochs")
    plt.ylabel("Loss Values")
    plt.legend()
    plt.title("Model Loss")
    plt.show()

def get_best_validation_metrics(history):
    """
    Extracts and prints the best values for multiple validation metrics from training history.

    Args:
    history (History): Training history object.

    Returns: The function directly prints the best validation metrics.
    None
    """
    metrics = ['val_accuracy']


    print("Best Validation Metrics:")
    for metric in metrics:
        best_value = np.max(history.history[metric])
        print(f"{metric.upper()}: {best_value:.4f}")

def predict_random_image(model, data_directory, classes, target_size=(128, 128)):
    """
    Predict and visualize a randomly selected image from the dataset.

    Args:
    model (Sequential): The trained model.
    data_directory (str): Path to the dataset directory.
    classes (list): List of class names.
    target_size (tuple): Desired image size.

    Returns:
    tuple: Actual class, image file name, predicted class, and class probabilities.
    """
    class_dirs = os.listdir(data_directory)
    random_class = random.choice(class_dirs)
    class_dir = os.path.join(data_directory, random_class)

    # Ensure the random_class is actually a directory and not a stray file
    while not os.path.isdir(class_dir):
        random_class = random.choice(class_dirs)
        class_dir = os.path.join(data_directory, random_class)
        if not class_dirs: # Avoid infinite loop if data_directory is empty
             raise ValueError("No class directories found in the dataset.")


    images = os.listdir(class_dir)

    # Filter out non-image files if any (basic check)
    image_files = [img for img in images if img.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp'))]
    if not image_files:
        raise ValueError(f"No image files found in directory: {class_dir}")

    random_image_file = random.choice(image_files) # Select a random *image file*
    image_path = os.path.join(class_dir, random_image_file) # Construct the full path to the image file

    if not os.path.exists(image_path):
        raise FileNotFoundError(f"The specified image path does not exist: {image_path}")

    img = cv2.imread(image_path)
    if img is None:
        raise ValueError(f"Unable to read the image file: {image_path}")

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, target_size)
    img_scaled = img_resized / 255.0
    img_expanded = np.expand_dims(img_scaled, axis=0)

    predictions = model.predict(img_expanded)
    predicted_class = np.argmax(predictions, axis=1)

    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(img_rgb)
    # Use the actual random class name for the title
    plt.title(f"Actual: {random_class}")
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.barh(range(len(classes)), predictions[0])
    # Ensure class indices are aligned with the classes list
    plt.yticks(range(len(classes)), classes)
    plt.xlabel('Probability')
    # Use the actual predicted class name from the classes list
    plt.title(f"Predicted: {classes[predicted_class[0]]}")

    plt.subplots_adjust(wspace=0.5)

    plt.show()

    return random_class, random_image_file, predicted_class[0], predictions

# def predict_random_image(model, data_directory, classes, target_size=(128, 128)):
#     """
#     Predict and visualize a randomly selected image from the dataset.

#     Args:
#     model (Sequential): The trained model.
#     data_directory (str): Path to the dataset directory.
#     classes (list): List of class names.
#     target_size (tuple): Desired image size.

#     Returns:
#     tuple: Actual class, image file name, predicted class, and class probabilities.
#     """
#     class_dirs = os.listdir(data_directory)
#     random_class = random.choice(class_dirs)
#     class_dir = os.path.join(data_directory, random_class)
#     images = os.listdir(class_dir)
#     random_image = random.choice(images)
#     image_path = os.path.join(class_dir, random_image)

#     if not os.path.exists(image_path):
#         raise FileNotFoundError(f"The specified image path does not exist: {image_path}")

#     img = cv2.imread(image_path)
#     if img is None:
#         raise ValueError(f"Unable to read the image file: {image_path}")

#     img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#     img_resized = cv2.resize(img_rgb, target_size)
#     img_scaled = img_resized / 255.0
#     img_expanded = np.expand_dims(img_scaled, axis=0)

#     predictions = model.predict(img_expanded)
#     predicted_class = np.argmax(predictions, axis=1)

#     plt.figure(figsize=(10, 5))

#     plt.subplot(1, 2, 1)
#     plt.imshow(img_rgb)
#     plt.title(f"Actual: {random_class}")
#     plt.axis('off')

#     plt.subplot(1, 2, 2)
#     plt.barh(range(len(classes)), predictions[0])
#     plt.yticks(range(len(classes)), classes)
#     plt.xlabel('Probability')
#     plt.title(f"Predicted: {classes[predicted_class[0]]}")

#     plt.subplots_adjust(wspace=0.5)

#     plt.show()

#     return random_class, random_image, predicted_class[0], predictions

def main():
    # data_directory = r"C:\Users\PC\Desktop\Cityscape Dataset" # Bu yol yanlış olabilir
    data_directory = "skycity_dataset"    # Güncellenmiş yol

    # Verileri yükle ve hazırla
    classes, label_classes = data_load(data_directory) # data_directory yolundan verileri yükle
    train_generator, validation_generator = data_prep(data_directory=data_directory, classes=classes) # eğitim ve doğrulama verilerini hazırla

    # Verileri eğitim ve doğrulama kümelerine ayır
    X_train, y_train = split_data(train_generator) # eğitim verilerini ayır
    X_test, y_test = split_data(validation_generator) # doğrulama verilerini ayır

    # Etiketleriyle birlikte bazı görüntüleri görselleştir
    visualize_images_with_labels(data_directory, num_images=20, font_size=20) # 20 görseli etiketleriyle göster

    # Modeli oluştur ve eğit
    model = build_model(input_shape=(128, 128, 3), num_classes=len(classes)) # modeli oluştur
    model.summary() # model özetini yazdır
    model, history = train_model_with_best_accuracy(model, X_train, y_train, X_test, y_test, epochs=50, checkpoint_path='best_model.keras') # modeli eğit ve en iyi modeli kaydet

    # Doğruluk ve kaybı çiz
    plot_accuracy(history) # doğruluk grafiğini çiz
    plot_loss(history) # kayıp grafiğini çiz

    # Veri kümesinden rastgele bir görüntüyü tahmin et
    random_class, random_image, predicted_class, predictions = predict_random_image(model, data_directory, classes) # rastgele bir görüntü seç ve tahmin et
    print(f"Rastgele seçilen görüntü '{random_class}' sınıfından: {random_image}") # tahmin edilen sınıfı yazdır
    print("Tahmin edilen sınıf:", predicted_class) # tahmin edilen sınıfı yazdır
    print("Sınıf olasılıkları:", predictions) # sınıf olasılıklarını yazdır

    get_best_validation_metrics(history) # en iyi doğrulama metriklerini al

if __name__ == "__main__":
    main()